[package]
name = "kaspa-wallet-grpc-core"
rust-version.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
include.workspace = true

[dependencies]
kaspa-wallet-core.workspace = true
tonic.workspace = true
prost.workspace = true

[lints]
workspace = true

[build-dependencies]
tonic-build = { workspace = true, features = ["prost"] }
