//! Wire format for unsigned and partially-signed transactions.
//!
//! The on-disk / on-wire format is protobuf-3, with the schema
//! vendored in the workspace at `wallet/grpc/core/proto/wallet.proto`
//! and the Rust types generated by `prost-build` in the
//! `kaspa-wallet-grpc-core` crate. This module re-exports those
//! generated types under `wire::*` and provides the encode/decode
//! entry points consumed by the parse and signing paths.
//!
//! Proto3's canonical encoding is deterministic for the same
//! logical message; the encode/decode round-trip and structural
//! shape are exercised by the in-tree tests, and cross-
//! implementation byte-equality is the gate exercised by the
//! parity tests under `kaspawallet/tests/`.

mod codec;
mod error;

#[cfg(test)]
mod tests;

/// Prost-generated wire types for the partial-signed-transaction
/// format. Re-exported from `kaspa-wallet-grpc-core` so consumers
/// in this crate refer to the types without taking a direct
/// dependency on the codegen output directory.
pub use kaspa_wallet_grpc_core::protoserialization as wire;

pub use codec::{deserialize_partially_signed_transaction, serialize_partially_signed_transaction};
pub use error::SerializationError;
